@startuml class-relationship

package "Arrows" {
    left to right direction
    ArrowTypes -- Solid
    ArrowTypes .. Dotted    
    ArrowTypes #-- ClassN
    ArrowTypes }-- ClassP
    ArrowTypes +-- ClassR
    ArrowTypes <--> ClassT
}

package "Relationship" {
    left to right direction

    class Dog extends Animal
    Animal <|-- Dog: Inheritance


    class Customer {
        - String name;
        - List<Order> orders;
    }

    class Order {
        - String orderID;
    }
    Customer "1" --> "0..*" Order : Association


    class Car {
        - Engine engine;
    }
    class Engine {
        - String type;
    }    
    Car *-- Engine : Composition of (Car has a Engine)



    class Department {
        - List<Professor> professors;
    }

    class Professor {
        - String name;
    }
    Department o-- Professor : Aggregation



    interface Shape <<interface>> 
    class Circle implements Shape {}
    Shape <|.. Square: Realization \n Interface Implementation
}


package "Arrow Customization" {
    left to right direction
    Class01 <-[#red,thickness=3]-> Class02
    Class01 -[#blue,dotted,bold]-> Class04 : Blue dashed
    Class01 "1" --> "0..*" Class06: Cardinality
    Class01 -left[hidden]- Class08: Hidden line for adjustment
}
        
@endum