@startuml class-relationship

package "Arrows" {
    left to right direction
    ArrowTypes -- Solid
    ArrowTypes .. Dotted    
    ArrowTypes #-- ClassN
    ArrowTypes }-- ClassP
    ArrowTypes +-- ClassR
    ArrowTypes <--> ClassT
}

package "Relationship" {
    left to right direction


    ClassE <|-- ClassF: Inheritance
    ClassG <-- ClassH : Association
    ClassI *-- ClassJ : Composition
    ClassK o-- ClassL : Aggregation
    ClassU <|.. ClassV: Implementation

    class ArrayList implements List
    class ArrayList extends AbstractList

}


package "Arrow Customization" {
    left to right direction
    Class01 <-[#red,thickness=3]-> Class02
    Class01 -[#blue,dotted,bold]-> Class04 : Blue dashed
    Class01 "1" --> "0..*" Class06: Cardinality
    Class01 -left[hidden]- Class08: Hidden line for adjustment
       
}
        
    


@endum